services:
  student-performance-predictor-env:
    platform: linux/amd64
    image: nhantien/student-performance-predictor:v0.4.0
    ports:
      - "8889:8888" # map port 8889 on host computer to 8888 in container
    volumes:
      - .:/home/jovyan/work
    container_name: student-performance-predictor