name: 522-project-env
channels:
  - conda-forge
dependencies:
  - python=3.11.9
  - numpy
  - pandas
  - pandera
  - deepchecks
  - matplotlib
  - altair
  - nbconvert
  - seaborn
  - scikit-learn
  - jupyterlab
  - ipykernel
  - xgboost
  - pip
  - pip:
      - altair-ally
