name: 522-project-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - conda-lock
  - numpy
  - pandas
  - matplotlib
  - altair
  - nbconvert
  - seaborn
  - scikit-learn
  - jupyterlab
  - ipykernel
  - xgboost
  - nb_conda_kernels
  - pip
  - pip:
      - altair-ally