name: 522-project-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=2.1.3
  - pandas=2.2.3
  - pandera=0.21.1
  - matplotlib=3.9.3
  - altair=5.5.0
  - nbconvert=7.16.4
  - seaborn=0.13.2
  - scikit-learn=1.5.2
  - jupyterlab=4.3.2
  - ipykernel=6.29.5
  - xgboost=2.1.3
  - click=8.1.7
  - tabulate=0.9.0
  - quarto=1.5.57
