project:
  type: website
  output-dir: ../docs

website:
  title: "Predicting academic performance using demographic and behavioral Data"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



